### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by gewahlt** [sherzaad/LIN#3]
arduino IDE 2.3
arduino nano

is it possible to use your LIN library.h in conjunction with AltSoftSerial.h? it is not possible to use LIN0. the code is not collected.

**Comment by sherzaad** [comment]
hello,
As far as I am aware, an Arduino nano has only ONE serial port. LIN1 (aka Serial1) would therefore not be available for that board.
Regards,
Sherzaad
    On Saturday 3 August 2024 at 19:32:08 BST, gewahlt ***@***.***> wrote:  
 
 


arduino IDE 2.3
arduino nano

it throws an error during the build of the example...

error: request for member 'begin' in 'LIN1', which is of non-class type 'int'
error: request for member 'available' in 'LIN1', which is of non-class type 'int'
error: request for member 'read' in 'LIN1', which is of non-class type 'int'
